languageCode = "de"
languageName = "Deutsch"
languageDirection = "ltr"
weight = 2

baseURL = "https://jneidel.de"

[params]
  dateFormat = "2. Jan 2006"
  mainSections = ["essay", "guide", "review", "project", "misc"]
  description = "Ein Website Ã¼ber das was funktioniert."

# [params.author]
  # headline = ""
  # bio = ""
