# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Essays"
  pageRef = "essay"
  weight = 10

[[main]]
  name = "Guides"
  pageRef = "guide"
  weight = 21

# [[main]]
#   name = "Reviews"
#   pageRef = "review"
#   weight = 40

[[main]]
  name = "Projects"
  pageRef = "project"
  weight = 30

# [[main]]
#   name = "RSS"
#   url = "/rss/"
#   weight = 92
#   title = "Subscribe via RSS"
#   [main.params]
#     icon = "rss"
#     showName = false
#     target = "_self"
#
[[main]]
  identifier = "search"
  weight = 90
  title = "Search this website"
  [main.params]
    action = "search"

[[main]]
  identifier = "appearance"
  weight = 95
  [main.params]
    action = "appearance"

[[main]]
  identifier = "locale"
  weight = 100
  title = "Switch locale"
  [main.params]
    action = "locale"

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
  name = "Privacy policy"
  pageRef = "privacy"
  weight = 10
