colorScheme = "jneidel"
defaultAppearance = "light" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true
enableImageLazyLoading = true
enableImageWebp = true
enableQuicklink = true

# robots = ""
fingerprintAlgorithm = "sha256"

[header]
  layout = "custom" # valid options: basic, hamburger, hybrid, custom
  logo = "img/logo.png"
  # logoDark = "img/logo-dark.png"
  showTitle = true
  # customLogos: given "recipe", on /recipe routes the img/logo-recipe.png is used
  customLogos = [ "recipe", "dev", "newsletter" ]

[footer]
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "page" # valid options: page, profile, custom
  showRecent = true
  recentLimit = 500

[author]
  name = "Jonathan Neidel"
  image = "img/author.jpg"
  # bio = 'Get in touch with me'
  email = "web@jneidel.com"
  links = [
    { email = "mailto:web@jneidel.com" },
    { gpg = "/gpg.txt" },
    { rss = "/rss/" },
  ]

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = true
  showBreadcrumbs = true # see: https://yoast.com/breadcrumbs-seo
  showDraftLabel = true
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showWordCount = false
  showTableOfContents = true
  showTaxonomies = true
  showComments = false

  # edit on github
  showEdit = true
  editURL = "https://github.com/jneidel/jneidel.com/tree/master/content/"
  editAppendPath = true

[list]
  showBreadcrumbs = true
  showTableOfContents = true
  showTaxonomies = false
  showSummary = true
  groupByYear = false
  paginationWidth = 1

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true

[fathomAnalytics]
  # site = "ABC12345"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""

[render_hooks.link]
  errorLevel = 'warning'
  highlightBroken = true
[render_hooks.image]
  errorLevel = 'warning'
