# See help and documentation at: https://nikitabobko.github.io/aerospace/guide
# Note that the modifier "alt" is invoked by the "option" key.

### Configuration
start-at-login = true

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[mode.main.binding]
# change focus: option + h/j/k/l
alt-h = 'focus --boundaries-action wrap-around-the-workspace left'
alt-j = 'focus --boundaries-action wrap-around-the-workspace down'
alt-k = 'focus --boundaries-action wrap-around-the-workspace up'
alt-l = 'focus --boundaries-action wrap-around-the-workspace right'

# move window: option + H/J/K/L
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# change layout
alt-s = 'layout v_accordion' # option + s = vertical tabs
alt-w = 'layout h_accordion' # option + w = horizontal tabs
alt-e = 'layout tiles horizontal vertical' # option + e = change between vertical and horizontal splits

alt-f = 'fullscreen' # option + f to toggle fullscreen
alt-space = 'layout floating tiling' # toggle between floating and regular window

# go to workspace
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'

# send active window to to workspace
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'

# interactively resize split
alt-r = 'mode resize'
[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'
q = 'mode main'


# Move app windows to specific workspaces.
# My workspace assignment is the same as on Linux:
# Workspace 1: Emacs
# Workspace 2: Browser
# Workspace 3: Terminal
# Workspace 4: Communication
# Workspace 5: Misc

# You can find out the app id in Karabiner EventViewer or if the app
# is running using: $ aerospace list-apps

# uncomment to activate
# [[on-window-detected]]
# if.app-id = 'org.gnu.Emacs'
# run = ['move-node-to-workspace 1']

# [[on-window-detected]]
# if.app-id = 'org.chromium.Chromium'
# run = ['move-node-to-workspace 2']

# [[on-window-detected]]
# if.app-id = 'net.kovidgoyal.kitty'
# run = ['move-node-to-workspace 3']

# [[on-window-detected]]
# if.app-id = 'com.microsoft.teams2'
# run = ['move-node-to-workspace 4']

# [[on-window-detected]]
# if.app-id = 'com.apple.mail'
# run = ['move-node-to-workspace 5']
